// In a new file: utils/username-generator.ts

export function generateRandomUsername(): string {
  const adjectives = [
    "Happy",
    "Clever",
    "Brave",
    "Bright",
    "Calm",
    "Eager",
    "Fair",
    "Fancy",
    "Quick",
    "Quiet",
    "Kind",
    "Lively",
    "Proud",
    "Silly",
    "Witty",
    "Warm",
    "Wise",
    "Zany",
    "Keen",
    "Noble",
    "Busy",
    "Cozy",
    "Cute",
    "Epic",
    "Jolly",
    "Mega",
    "Neat",
    "Nice",
    "Posh",
    "Rich",
    "Safe",
    "Soft",
    "Vast",
    "Bold",
    "Cool",
    "Easy",
    "Free",
    "Glad",
    "Gold",
    "Good",
    "Able",
    "Ace",
    "Big",
    "Fit",
    "Fun",
    "Hip",
    "Hot",
    "Key",
    "New",
    "Rad",
  ];

  const nouns = [
    "Apple",
    "Bread",
    "Cloud",
    "Dream",
    "Eagle",
    "Flame",
    "Grass",
    "Heart",
    "Idea",
    "Joke",
    "Kite",
    "Lemon",
    "Moon",
    "Nest",
    "Ocean",
    "Peach",
    "Queen",
    "River",
    "Star",
    "Tree",
    "Umbrella",
    "Violin",
    "Water",
    "Xylophone",
    "Yacht",
    "Zebra",
    "Acorn",
    "Bear",
    "Cat",
    "Dog",
    "Elk",
    "Fox",
    "Goat",
    "Hawk",
    "Iguana",
    "Jay",
    "Koala",
    "Lion",
    "Mouse",
    "Newt",
    "Owl",
    "Panda",
    "Quail",
    "Rabbit",
    "Sheep",
    "Tiger",
    "Urchin",
    "Vole",
    "Wolf",
    "Yak",
  ];

  // Select random adjective and noun
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];

  // Generate 4 random digits
  const num = String(Math.floor(Math.random() * 10000)).padStart(4, "0");

  // Combine to form username
  return `${adj}${noun}${num}`;
}
